### ISSUE TITLE
UBO Port

### ISSUE THREAD

**Issue by GeraldKimmersdorfer** [weBIGeo/webigeo#6]
**Issue includes:**
- Setup the existing Uniform Buffer Classes (in glengine) such that they work in WebGPU
- Some Shader Setup to verify the correct implementation
- Optional: Move the general container into the nucleus?

**Goal:**
- Parameters can be sent to shader via a UBO

**Non-Goals:**
- Implement any of the effects/shaders which the UBOs are for

**Comment by pkomon-tgm** [comment]
This seems to be done 🎉 (for quite a while now, just forgot to update here)

As it is now, I would not move the buffer code into nucleus, because it still depends on webGPU specifics. I'm not sure whether we can come up with a generic interface that is useful, simple and independent of the graphics API.
